/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.model.ChangePasswordRequest;
import io.swagger.client.model.CreateUserRequest;
import io.swagger.client.model.User;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for UserApiServiceApi
 */
@Ignore
public class UserApiServiceApiTest {

    private final UserApiServiceApi api = new UserApiServiceApi();

    /**
     * Cambiar contraseña de usuarios
     *
     * Cambiar contraseña un usuario a partir de un Id y una password antigua y otra nueva
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void cambiarContraseaTest() throws Exception {
        ChangePasswordRequest body = null;
        api.cambiarContrasea(body);

        // TODO: test validations
    }
    /**
     * Consulta de usuarios
     *
     * Consultar un usuario a partir de un ID
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void consultarUsuarioTest() throws Exception {
        Object id = null;
        User response = api.consultarUsuario(id);

        // TODO: test validations
    }
    /**
     * Crear usuario
     *
     * Crear un usuario
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void crearUsuarioTest() throws Exception {
        CreateUserRequest body = null;
        User response = api.crearUsuario(body);

        // TODO: test validations
    }
    /**
     * Consulta de usuarios
     *
     * Consultar un usuario a partir de un login y password
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void loginUsuarioTest() throws Exception {
        Object login = null;
        Object password = null;
        User response = api.loginUsuario(login, password);

        // TODO: test validations
    }
}
