/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.ChangePasswordRequest;
import org.openapitools.client.model.CreateUserRequest;
import org.openapitools.client.model.User;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for UserApiServiceApi
 */
@Disabled
public class UserApiServiceApiTest {

    private final UserApiServiceApi api = new UserApiServiceApi();

    /**
     * Cambiar contraseña de usuarios
     *
     * Cambiar contraseña un usuario a partir de un Id y una password antigua y otra nueva
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void cambiarContraseaTest() throws ApiException {
        ChangePasswordRequest changePasswordRequest = null;
        api.cambiarContrasea(changePasswordRequest);
        // TODO: test validations
    }

    /**
     * Consulta de usuarios
     *
     * Consultar un usuario a partir de un ID
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void consultarUsuarioTest() throws ApiException {
        Long id = null;
        User response = api.consultarUsuario(id);
        // TODO: test validations
    }

    /**
     * Crear usuario
     *
     * Crear un usuario
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void crearUsuarioTest() throws ApiException {
        CreateUserRequest createUserRequest = null;
        User response = api.crearUsuario(createUserRequest);
        // TODO: test validations
    }

    /**
     * Consulta de usuarios
     *
     * Consultar un usuario a partir de un login y password
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void loginUsuarioTest() throws ApiException {
        String login = null;
        String password = null;
        User response = api.loginUsuario(login, password);
        // TODO: test validations
    }

}
