/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * ChangePasswordRequest
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-01-29T18:51:26.138767027Z[GMT]")

public class ChangePasswordRequest {
  @SerializedName("id")
  private Object id = null;

  @SerializedName("passwordOld")
  private Object passwordOld = null;

  @SerializedName("passwordNew")
  private Object passwordNew = null;

  public ChangePasswordRequest id(Object id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(description = "")
  public Object getId() {
    return id;
  }

  public void setId(Object id) {
    this.id = id;
  }

  public ChangePasswordRequest passwordOld(Object passwordOld) {
    this.passwordOld = passwordOld;
    return this;
  }

   /**
   * Get passwordOld
   * @return passwordOld
  **/
  @Schema(description = "")
  public Object getPasswordOld() {
    return passwordOld;
  }

  public void setPasswordOld(Object passwordOld) {
    this.passwordOld = passwordOld;
  }

  public ChangePasswordRequest passwordNew(Object passwordNew) {
    this.passwordNew = passwordNew;
    return this;
  }

   /**
   * Get passwordNew
   * @return passwordNew
  **/
  @Schema(description = "")
  public Object getPasswordNew() {
    return passwordNew;
  }

  public void setPasswordNew(Object passwordNew) {
    this.passwordNew = passwordNew;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ChangePasswordRequest changePasswordRequest = (ChangePasswordRequest) o;
    return Objects.equals(this.id, changePasswordRequest.id) &&
        Objects.equals(this.passwordOld, changePasswordRequest.passwordOld) &&
        Objects.equals(this.passwordNew, changePasswordRequest.passwordNew);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, passwordOld, passwordNew);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ChangePasswordRequest {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    passwordOld: ").append(toIndentedString(passwordOld)).append("\n");
    sb.append("    passwordNew: ").append(toIndentedString(passwordNew)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
